### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by javiermortiz** [tedjanton/Brewd#1]
Looks good! I would divide feature 3 into two separate feature: Coffee crud and check in crud. Even though sometimes they are created simultaneously, sometimes they are not, and you will have 2 different database so I think is worth making that distinction.

**Comment by tedjanton** [comment]
@javiermortiz Thanks for the feedback! Quick clarification...the way we were planning on doing this was having a "coffee check-in" be one thing. A user "checks in" a coffee they are drinking and adds an optional comment/rating with their check in just like on UNTAPPD. They don't have the ability to "create" a new coffee, so I'm not sure how we would split it into 2 separate features.

**Comment by tedjanton** [comment]
Solved with offline discussion.
